### ISSUE TITLE
Player's score is unsigned when it should be signed

### ISSUE THREAD

**Issue by ashort96** [rumblefrog/a2s-rs#9]
https://github.com/rumblefrog/a2s-rs/blob/bfb7dd52d8fbbac184ddb64ebb6f7e936a0dbfdd/src/players.rs#L37

In the Server queries documentation from Valve, a [player's score](https://developer.valvesoftware.com/wiki/Server_queries#Response_Format_2) is a long, or a signed integer.

**Comment by rumblefrog** [comment]
Can a player's score really be negative? Doesn't make sense to use signed here despite their documentation.

**Comment by ashortdc** [comment]
Yep - if a player kills themself, their score can go in the negative.

**Comment by ashort96** [comment]
Yep - if a player kills themselves, their score can go negative.

**Comment by rumblefrog** [comment]
Got it, thanks!
